In [ ]:
import numpy as np

# Breve introducción a numpy

El objeto base de los numpy son los arrays N dimensionales. `ndarray`

Se pueden crear arrays a partir de listas de python:

In [ ]:
#lista de python:
plist=[1,2,3,4,5]
plist

[1, 2, 3, 4, 5]

In [ ]:
#array de numpy:
a1D=np.array(plist)
a1D

array([1, 2, 3, 4, 5])

A diferencia de las listas de python los arrays de numpy soportan operaciones aritméticas.

## Aritmética contra escalares

se aplican a cada coordenada contra el escalar

In [ ]:
#Producto por un escalar
a1D*2

array([ 2,  4,  6,  8, 10])

In [ ]:
#Suma contra un escalar
a1D+1

array([2, 3, 4, 5, 6])

In [ ]:
#Potenciación
a1D**2

array([ 1,  4,  9, 16, 25])

## Aritmética array a array

In [ ]:
b1D=np.array([5,4,3,2,1])
b1D

array([5, 4, 3, 2, 1])

In [ ]:
#suma
a1D+b1D

array([6, 6, 6, 6, 6])

In [ ]:
#producto
a1D*b1D

array([5, 8, 9, 8, 5])

In [ ]:
#potenciación
a1D**b1D

array([ 1, 16, 27, 16,  5])

## Operaciones Vectoriales

In [ ]:
#Producto escalar. Se hace mediante el operador arroba
a1D @ b1D

35

In [ ]:
#Vemos que coincide con la suma del producto coordenada a coordenada
(a1D*b1D).sum()

35

In [ ]:
#Ademas del operador @ llama a la función dot()
np.dot(a1D,b1D)

35

## Funciones en numpy, parte 1

en la sección de arriba vimos dot() y sum(). La mayoría de las funciones que reciben un array como argumento pueden llamarse como función o como método del objeto array

In [ ]:
np.sum(a1D)

15

In [ ]:
a1D.sum()

15

Otras funciones típicas

In [ ]:
#media
a1D.mean()

3.0

In [ ]:
#varianza
a1D.var()

2.0

In [ ]:
#exponenciación (e elevado a los numeros del array)
np.exp(1)

2.718281828459045

## Dimensiones

Los arrays pueden tener K dimensiones.  Comencemos con el caso mas sencillo de 2 dimensiones, pero las operaciones pueden generalizar independientemente del número de dimensiones:

In [ ]:
#Los arrays pueden formarse a partir de listas de listas
a2D=np.array([[1,2,3],[4,5,6]])
a2D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#A partir de 2 dimensiones podemos transponer los arrays. De nuevo hay 3 sabores para esto:

np.transpose(a2D)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a2D.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a2D.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#El producto punto esta definido también para múltiples dimensiones, y resulta en el producto matricial:

a2D.T @ a2D

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [ ]:
a2D @ a2D.T

array([[14, 32],
       [32, 77]])

Podemos obtener infomación de las dimensiones de un array

In [ ]:
#Numero de dimensiones
a2D.ndim

2

In [ ]:
#Cardinalidad en cada dimensión
a2D.shape

(2, 3)

In [ ]:
#Candtidad de elementos totales
a2D.size

6

In [ ]:
#Size coincide con la productoria de las cardinalidades.
np.prod(a2D.shape)

6

## Generación de arrays

In [ ]:
#el operador range en python produce un generator, que es lento.
#En numpy es mejor usar arange, que tiene la misma interface que range()
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
#Tambien funciona definiendo rangos
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
#Muy utiles son tambien la generación de zeros y unos.


np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#Ambas funciones reciben una tupla de cardinalidades (o shape) como argumento
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#La funcion eye generar una matriz identidad:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#la funcion diag, genera una matriz diagonal a partir de un array
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## Cambio de dimensionalidad

In [ ]:
a100=np.arange(100)
a100

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
#La función reshape permite cambiar la dimension
aC=np.reshape(a100,(10,10))
aC

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
#Reshape acepa que una cardinalidad sea -1, autocompletanndo esa dimension para que "cierre"
np.reshape(a100,(10,-1,5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

## Indexación:

In [ ]:
as10=np.arange(0,100,10)
as10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#numpy acepta python slices
#la syntaxis es comienzo : fin
as10[1:5]

array([10, 20, 30, 40])

In [ ]:
#notar que el valor del final es exclusivo, es decir as10[5] no esta incluido en el silice anterior
as10[5]

50

In [ ]:
#si un valor del slice no se elije se utiliza los valores por defecto
#0 para el comienzo
as10[:5]

array([ 0, 10, 20, 30, 40])

In [ ]:
#la cardinalidad para el fin
as10[3:]


array([30, 40, 50, 60, 70, 80, 90])

In [ ]:
#tambien se aceptan valores negativos para indicar para indicar la cardinalidad - n
#por ejemplo para quitar el ultimo valor
as10[:-1]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
#La sintaxis de slices acepta un 3er parametro llamado stride, que es el paso,
# por ejemplo para quedarnos con los elementos pares
as10[::2]

array([ 0, 20, 40, 60, 80])

In [ ]:
#y para los impares, arrancamos con el primero
as10[1::2]

array([10, 30, 50, 70, 90])

In [ ]:
# el stride puede ser negativo, lo que invierte el array
as10[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

In [ ]:
#numpy acepta indexacion multidimensional, por ejemplo para
aC

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
#Podemos definir ambas coordenadas en el mismo corchete
aC[0,1]

1

In [ ]:
aC[1,0]

10

In [ ]:
#La indexación multidmensional tambien acepta slices, por ejemplo:
#Para cortar en la 5ta fila y la 3ra columna
aC[:5,:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]])

In [ ]:
#Si queremos dejar una dimensión completa, se dejan los ":" vacios 
#para indicar que vamos desde 0 hasta la cardinalidad.

#Por ejemplo para quedarnos con la 3ra columna

aC[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [ ]:
#Para la 3ra y 4ta
aC[:,3:5]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44],
       [53, 54],
       [63, 64],
       [73, 74],
       [83, 84],
       [93, 94]])

## Asignación:

los operadores de signacion =, +=, etc, pueden ser aplicados contra las selecciones

In [ ]:
aC

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
#Incrementa las 3 primeras
aC[:3] = aC[:3]+1
aC

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
#Asigna 0 a la ultimas 3 columnas
aC[:,-3:]=0
aC

array([[ 0,  1,  2,  3,  4,  5,  6,  0,  0,  0],
       [10, 11, 12, 13, 14, 15, 16,  0,  0,  0],
       [20, 21, 22, 23, 24, 25, 26,  0,  0,  0],
       [30, 31, 32, 33, 34, 35, 36,  0,  0,  0],
       [40, 41, 42, 43, 44, 45, 46,  0,  0,  0],
       [50, 51, 52, 53, 54, 55, 56,  0,  0,  0],
       [60, 61, 62, 63, 64, 65, 66,  0,  0,  0],
       [70, 71, 72, 73, 74, 75, 76,  0,  0,  0],
       [80, 81, 82, 83, 84, 85, 86,  0,  0,  0],
       [90, 91, 92, 93, 94, 95, 96,  0,  0,  0]])

In [ ]:
#Multiplica por 2 las ultimas 2 filas
aC[-2:]*=2
aC

array([[  0,   1,   2,   3,   4,   5,   6,   0,   0,   0],
       [ 10,  11,  12,  13,  14,  15,  16,   0,   0,   0],
       [ 20,  21,  22,  23,  24,  25,  26,   0,   0,   0],
       [ 30,  31,  32,  33,  34,  35,  36,   0,   0,   0],
       [ 40,  41,  42,  43,  44,  45,  46,   0,   0,   0],
       [ 50,  51,  52,  53,  54,  55,  56,   0,   0,   0],
       [ 60,  61,  62,  63,  64,  65,  66,   0,   0,   0],
       [ 70,  71,  72,  73,  74,  75,  76,   0,   0,   0],
       [160, 162, 164, 166, 168, 170, 172,   0,   0,   0],
       [180, 182, 184, 186, 188, 190, 192,   0,   0,   0]])

## Indexacion avanzada

Ademas de slices se puede indexar utilizando listas de booleanos o indices.

### Indexación por listas

Por ejemplo, para quedarnos con las filas 3,6,y 8

In [ ]:
aC=np.arange(100).reshape((10,10))
aC

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
aC[[3,6,8]]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

El orden tambien puede variar

In [ ]:
aC[[8,3,6]]

array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

### Indexación booleana

Por otro lado, la indexación booleana es buena para el filtrado o para armar mascaras... Por ejemplo, generemos una matriz de numeros ordenados aleatoreamente:

In [ ]:
rC=np.random.choice(100,100,replace=False).reshape(10,10)
rC

array([[17, 67, 80, 64, 38, 61, 97, 77, 83, 75],
       [71, 21, 42, 19, 49, 70, 95, 92, 32,  5],
       [18, 40, 45, 96, 98, 66, 86, 24, 72, 11],
       [88,  7, 55, 59, 22, 60, 69, 68,  8, 73],
       [ 1, 35, 99, 12, 28, 50, 94, 23, 53, 52],
       [13,  9, 85, 58, 34,  0, 63, 84, 65, 46],
       [87, 31,  3, 29, 48, 15, 33, 41, 14, 30],
       [76, 54, 44, 47, 90, 62, 78, 10, 74, 93],
       [37, 43,  4, 81,  2, 25, 89, 79, 51, 91],
       [20, 26, 39, 36, 57, 82, 56, 16,  6, 27]])

In [ ]:
#Elegimos las filas que tengan valores mayores a 50 en la 4ta columna

rC[:,3]

array([64, 19, 96, 59, 12, 58, 29, 47, 81, 36])

In [ ]:
rC[:,3]>50

array([ True, False,  True,  True, False,  True, False, False,  True,
       False])

In [ ]:
rC[rC[:,3]>50, 3]

array([64, 96, 59, 58, 81])

## Axis

Casi todas las funciones de numpy aceptan el kwarg `axis` que indica la dimension sobre la cual se restringe una operación

In [ ]:
#Por ejemplo para
aC

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# maximo por columna:
aC.max(axis=1)

array([10, 20, 30, 39, 49, 59, 69, 79, 89, 99])

## Concatenación

Hay varios métodos:

In [ ]:
unos=np.ones((2,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Apilar vertical
np.vstack([unos,zeros])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Apilar horizontal
np.hstack([unos,zeros])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [ ]:
#Agregar una columna a una matriz con hstack se complica, para eso se puede usar column stack
np.column_stack([unos,[3,4]])

array([[1., 1., 1., 3.],
       [1., 1., 1., 4.]])

In [ ]:
#Este es un caso tan frecuente que tiene su propio metodo
np.c_[unos,[3,4]]

array([[1., 1., 1., 3.],
       [1., 1., 1., 4.]])

La función `concatenate()` generaliza las operaciones de stacking para 3 o mas dimensiones.